name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *"   # har 24 soatda ishlaydi
  workflow_dispatch:        # manual run ham bo‘ladi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk@main
        with:
          github_user_name: MaxliyoAbbosxonova
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
